# Generated by Django 5.1.4 on 2025-01-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotilike', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date_sortie',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
