# Generated by Django 5.1.4 on 2025-02-02 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotilike', '0002_remove_morceau_morceau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='biographie',
        ),
    ]
